import { type Row } from "./columns";

export const rows: Row[] = [
  {
    decimal: 1,
    morse: ".-",
    nato: "alfa",
    semaphore: [180, 225],
    braille: "\u2801",
  },
  {
    decimal: 2,
    morse: "-...",
    nato: "bravo",
    semaphore: [180, 270],
    braille: "\u2803",
  },
  {
    decimal: 3,
    morse: "-.-.",
    nato: "charlie",
    semaphore: [180, 315],
    braille: "\u2809",
  },
  {
    decimal: 4,
    morse: "-..",
    nato: "delta",
    semaphore: [180, 0],
    braille: "\u2819",
  },
  {
    decimal: 5,
    morse: ".",
    nato: "echo",
    semaphore: [180, 45],
    braille: "\u2811",
  },
  {
    decimal: 6,
    morse: "..-.",
    nato: "foxtrot",
    semaphore: [180, 90],
    braille: "\u280B",
  },
  {
    decimal: 7,
    morse: "--.",
    nato: "golf",
    semaphore: [180, 135],
    braille: "\u281B",
  },
  {
    decimal: 8,
    morse: "....",
    nato: "hotel",
    semaphore: [225, 270],
    braille: "\u2813",
  },
  {
    decimal: 9,
    morse: "..",
    nato: "india",
    semaphore: [225, 315],
    braille: "\u280A",
  },
  {
    decimal: 10,
    morse: ".---",
    nato: "juliett",
    semaphore: [0, 90],
    braille: "\u281A",
  },
  {
    decimal: 11,
    morse: "-.-",
    nato: "kilo",
    semaphore: [0, 225],
    braille: "\u2805",
  },
  {
    decimal: 12,
    morse: ".-..",
    nato: "lima",
    semaphore: [225, 45],
    braille: "\u2807",
  },
  {
    decimal: 13,
    morse: "--",
    nato: "mike",
    semaphore: [225, 90],
    braille: "\u280D",
  },
  {
    decimal: 14,
    morse: "-.",
    nato: "november",
    semaphore: [225, 135],
    braille: "\u281D",
  },
  {
    decimal: 15,
    morse: "---",
    nato: "oscar",
    semaphore: [270, 315],
    braille: "\u2815",
  },
  {
    decimal: 16,
    morse: ".--.",
    nato: "papa",
    semaphore: [270, 0],
    braille: "\u280F",
  },
  {
    decimal: 17,
    morse: "--.-",
    nato: "quebec",
    semaphore: [270, 45],
    braille: "\u281F",
  },
  {
    decimal: 18,
    morse: ".-.",
    nato: "romeo",
    semaphore: [270, 90],
    braille: "\u2817",
  },
  {
    decimal: 19,
    morse: "...",
    nato: "sierra",
    semaphore: [270, 135],
    braille: "\u280E",
  },
  {
    decimal: 20,
    morse: "-",
    nato: "tango",
    semaphore: [315, 0],
    braille: "\u281E",
  },
  {
    decimal: 21,
    morse: "..-",
    nato: "uniform",
    semaphore: [315, 45],
    braille: "\u2825",
  },
  {
    decimal: 22,
    morse: "...-",
    nato: "victor",
    semaphore: [0, 135],
    braille: "\u2827",
  },
  {
    decimal: 23,
    morse: ".--",
    nato: "whiskey",
    semaphore: [45, 90],
    braille: "\u283A",
  },
  {
    decimal: 24,
    morse: "-..-",
    nato: "xray",
    semaphore: [45, 135],
    braille: "\u282D",
  },
  {
    decimal: 25,
    morse: "-.--",
    nato: "yankee",
    semaphore: [315, 90],
    braille: "\u283D",
  },
  {
    decimal: 26,
    morse: "--..",
    nato: "zulu",
    semaphore: [90, 135],
    braille: "\u2835",
  },
];
